In [0]:
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

In [0]:
import numpy as np
np.random.seed(42)

xs = 2 * np.random.rand(100, 1)
ys = 4 + 3 * xs + np.random.rand(100, 1)
zs = 2 * np.random.rand(100, 1)

In [0]:
# split the data into training and test sets
# train set
train_xs = xs[:80]
train_ys = ys[:80]
train_zs = zs[:80]
# test set
test_xs = xs[80:]
test_ys = ys[80:]
test_zs = zs[80:]

In [0]:
# number of epochs
epochs = 10
# learning rate
lr = 0.01

In [0]:
# initial value for weight w1, w2 and bias b
w1 = np.random.randn(1)
w2 = np.random.randn(1)
b = np.zeros(1)

In [0]:
for epoch in np.arange(epochs):
  for i in np.arange(80):
    y_pred = w1 * train_xs[i] + w2 * train_zs[i] + b
    
    grad_w1 = (y_pred - train_ys[i]) * train_xs[i]
    grad_w2 = (y_pred - train_ys[i]) * train_zs[i]
    grad_b = (y_pred - train_ys[i])
    
    w1 -= lr * grad_w1
    w2 -= lr * grad_w2
    b -= lr * grad_b

In [0]:
test_loss = 0
for i in np.arange(20):
  test_loss += 0.5 * (w1 * test_xs[i] + w2 * test_zs[i] + b - test_ys[i]) ** 2
test_loss /= 20

In [37]:
test_loss

array([0.18267746])

In [0]:
pred_ys = w1 * test_xs + w2 * test_zs + b

In [40]:
w1

array([3.31507402])

In [41]:
w2

array([0.45473112])

In [42]:
b

array([3.53793615])